services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: UsersInSystem
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: IU8_l1ver
    ports:
      - "5432:5432"
    restart: always
  app-3:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  app-1:
    image: sping_sec
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/UsersInSystem
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: IU8_l1ver
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always


  app-2:
   image: spa
   ports:
     - "3000:3000"
   restart: always





  